# Generated by Django 4.0 on 2021-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upvote_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
