version: "3.7"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    run:
      web: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    container_name: post_project
    command: bash -c "python manage.py gunicorn --bind 0.0.0.0:8000 main.wsgi"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - post_db

  django_migrate:
    image: crmbackend01/crm-image:${TAG}
    container_name: post_migrate
    command: bash -c "python manage.py migrate"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - post_db

  post_db:
    image: postgres:12
    container_name: database
    volumes:
    - ./pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
